rm px4-ads1115
rm px4-attitude_estimator_q
rm px4-battery_status
rm px4-bmm150
rm px4-cdev_test
rm px4-commander
rm px4-control_allocator
rm px4-controllib_test
rm px4-crsf_rc
rm px4-dataman
rm px4-ekf2
rm px4-flight_mode_manager
rm px4-gyro_calibration
rm px4-gyro_fft
rm px4-hrt_test
rm px4-icm42688p
rm px4-icp201xx
rm px4-land_detector
rm px4-landing_target_estimator
rm px4-listener
rm px4-load_mon
rm px4-local_position_estimator
rm px4-logger
rm px4-mag_bias_estimator
rm px4-manual_control
rm px4-mavlink
rm px4-mavlink_tests
rm px4-mc_att_control
rm px4-mc_autotune_attitude_control
rm px4-mc_hover_thrust_estimator
rm px4-mc_pos_control
rm px4-mc_rate_control
rm px4-navigator
rm px4-param
rm px4-pca9685_pwm_out
rm px4-rc_input
rm px4-rc_tests
rm px4-rc_update
rm px4-send_event
rm px4-sensors
rm px4-shutdown
rm px4-temperature_compensation
rm px4-tests
rm px4-uorb
rm px4-uorb_tests
rm px4-ver
rm px4-work_queue
rm px4-wqueue_test